/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SeasonsRouteImport } from './routes/seasons'
import { Route as RoundsRouteImport } from './routes/rounds'
import { Route as PlayersRouteImport } from './routes/players'
import { Route as ClockRouteImport } from './routes/clock'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SeasonsIdRouteImport } from './routes/seasons.$id'
import { Route as RoundsIdRouteImport } from './routes/rounds.$id'
import { Route as PlayersIdRouteImport } from './routes/players.$id'

const SeasonsRoute = SeasonsRouteImport.update({
  id: '/seasons',
  path: '/seasons',
  getParentRoute: () => rootRouteImport,
} as any)
const RoundsRoute = RoundsRouteImport.update({
  id: '/rounds',
  path: '/rounds',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersRoute = PlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => rootRouteImport,
} as any)
const ClockRoute = ClockRouteImport.update({
  id: '/clock',
  path: '/clock',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeasonsIdRoute = SeasonsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SeasonsRoute,
} as any)
const RoundsIdRoute = RoundsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RoundsRoute,
} as any)
const PlayersIdRoute = PlayersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PlayersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/clock': typeof ClockRoute
  '/players': typeof PlayersRouteWithChildren
  '/rounds': typeof RoundsRouteWithChildren
  '/seasons': typeof SeasonsRouteWithChildren
  '/players/$id': typeof PlayersIdRoute
  '/rounds/$id': typeof RoundsIdRoute
  '/seasons/$id': typeof SeasonsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/clock': typeof ClockRoute
  '/players': typeof PlayersRouteWithChildren
  '/rounds': typeof RoundsRouteWithChildren
  '/seasons': typeof SeasonsRouteWithChildren
  '/players/$id': typeof PlayersIdRoute
  '/rounds/$id': typeof RoundsIdRoute
  '/seasons/$id': typeof SeasonsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/clock': typeof ClockRoute
  '/players': typeof PlayersRouteWithChildren
  '/rounds': typeof RoundsRouteWithChildren
  '/seasons': typeof SeasonsRouteWithChildren
  '/players/$id': typeof PlayersIdRoute
  '/rounds/$id': typeof RoundsIdRoute
  '/seasons/$id': typeof SeasonsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/clock'
    | '/players'
    | '/rounds'
    | '/seasons'
    | '/players/$id'
    | '/rounds/$id'
    | '/seasons/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/clock'
    | '/players'
    | '/rounds'
    | '/seasons'
    | '/players/$id'
    | '/rounds/$id'
    | '/seasons/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/clock'
    | '/players'
    | '/rounds'
    | '/seasons'
    | '/players/$id'
    | '/rounds/$id'
    | '/seasons/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ClockRoute: typeof ClockRoute
  PlayersRoute: typeof PlayersRouteWithChildren
  RoundsRoute: typeof RoundsRouteWithChildren
  SeasonsRoute: typeof SeasonsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/seasons': {
      id: '/seasons'
      path: '/seasons'
      fullPath: '/seasons'
      preLoaderRoute: typeof SeasonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rounds': {
      id: '/rounds'
      path: '/rounds'
      fullPath: '/rounds'
      preLoaderRoute: typeof RoundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players': {
      id: '/players'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof PlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clock': {
      id: '/clock'
      path: '/clock'
      fullPath: '/clock'
      preLoaderRoute: typeof ClockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seasons/$id': {
      id: '/seasons/$id'
      path: '/$id'
      fullPath: '/seasons/$id'
      preLoaderRoute: typeof SeasonsIdRouteImport
      parentRoute: typeof SeasonsRoute
    }
    '/rounds/$id': {
      id: '/rounds/$id'
      path: '/$id'
      fullPath: '/rounds/$id'
      preLoaderRoute: typeof RoundsIdRouteImport
      parentRoute: typeof RoundsRoute
    }
    '/players/$id': {
      id: '/players/$id'
      path: '/$id'
      fullPath: '/players/$id'
      preLoaderRoute: typeof PlayersIdRouteImport
      parentRoute: typeof PlayersRoute
    }
  }
}

interface PlayersRouteChildren {
  PlayersIdRoute: typeof PlayersIdRoute
}

const PlayersRouteChildren: PlayersRouteChildren = {
  PlayersIdRoute: PlayersIdRoute,
}

const PlayersRouteWithChildren =
  PlayersRoute._addFileChildren(PlayersRouteChildren)

interface RoundsRouteChildren {
  RoundsIdRoute: typeof RoundsIdRoute
}

const RoundsRouteChildren: RoundsRouteChildren = {
  RoundsIdRoute: RoundsIdRoute,
}

const RoundsRouteWithChildren =
  RoundsRoute._addFileChildren(RoundsRouteChildren)

interface SeasonsRouteChildren {
  SeasonsIdRoute: typeof SeasonsIdRoute
}

const SeasonsRouteChildren: SeasonsRouteChildren = {
  SeasonsIdRoute: SeasonsIdRoute,
}

const SeasonsRouteWithChildren =
  SeasonsRoute._addFileChildren(SeasonsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ClockRoute: ClockRoute,
  PlayersRoute: PlayersRouteWithChildren,
  RoundsRoute: RoundsRouteWithChildren,
  SeasonsRoute: SeasonsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
